### ISSUE TITLE
Generation of invalid faust file

### ISSUE THREAD

**Issue by aliallaoui** [mi-creative/MIMS#1]
After generating a basic string and exporting it to a faust file, the compilation of the faust file fails :
 string.dsp : 40 : ERROR : syntax error, unexpected RBRAQ
FAUST Version 2.17.3, Ubuntu 18.04

**Comment by jameslnrd** [comment]
Seems to be caused when no sound output channels have been created. Should create a warning message for this / stop compilation for Faust DSP if no audio outputs are declared.
